CONFIG_CIRRUS_PLAYBACK=y
CONFIG_SND_SOC_CIRRUS_PLAYBACK=y
CONFIG_SND_SOC_TAS2562=y
CONFIG_SND_SOC_TAS256X=y
CONFIG_TAS256X_REGMAP=y
CONFIG_TAS256X_CODEC=y
CONFIG_TAS256X_MISC=y
CONFIG_TAS256X_REGBIN_PARSER=y
CONFIG_PLATFORM_QCOM=y
CONFIG_TAS25XX_ALGO=y
CONFIG_TAS25XX_ALGO_STEREO=y
CONFIG_TISA_KBIN_INTF=y
