# Cirrus Logic pinctrl drivers
obj-$(CONFIG_PINCTRL_MADERA)	+= pinctrl-madera.o
ifeq ($(CONFIG_PINCTRL_CS47L35),y)
obj-$(CONFIG_PINCTRL_MADERA)	+= pinctrl-cs47l35.o
endif
obj-$(CONFIG_PINCTRL_TACNA)	+= pinctrl-tacna.o
